### ISSUE TITLE
Predict('mycustommodel') doesn't work (empty model in service)

### ISSUE THREAD

**Issue by prcb** [PHPfanatic/clarifai#1]
This modification works (Line 159, ImageClient.php):

```
// Custom model handler.
if(!array_key_exists($model, $this->models)) {
	$this->models['Custom'] = $model;
	$service = 'models/' . $model . '/outputs';
}
else {
	$service = 'models/' . $this->models[$model] . '/outputs';
}
```

**Comment by PHPfanatic** [comment]
prcb,
Excellent find, thank you for the fix, I am including it in the main branch now and after it clears tests will be included in the next release.

Thank you again.

**Comment by keithslater** [comment]
This should be urlencoded in case there is a space in the model name

**Comment by PHPfanatic** [comment]
keithslater, 
That's a good point.  I was looking back through the code and it is a bit misleading on my library's side as its actually the model id that should be passed in for a custom model as my library is not storing or looking up the custom model by name.  Either way, I did test creating a custom model with spaces in the ID and to my surprise it is allowed.

I am in the middle of a version update and will address your urlencoding of the model ID, and additionally attempt to make the custom model more user-friendly.

Thank you for the input, it is appreciated.
