### ISSUE TITLE
Legacy authorization

### ISSUE THREAD

**Issue by nxtpl** [PHPfanatic/clarifai#4]
Clarifai states that used authorization method is now deprecated. Is it possible to update it to use API Keys?

> Note: Authorization through Client ID, Client Secret, and Access Tokens will soon be deprecated from the Clarifai platform, in exchange for API Keys. API Keys will enable you to generate authorization keys with finer scopes (e.g. predict only, add inputs and predict, etc.) for sharing and security purposes.

**Comment by PHPfanatic** [comment]
I am starting on an update for this issue.

**Comment by PHPfanatic** [comment]
This has been updated in the 2.0.0 release.  Thank you for the issue reminder.  If you have any further issues or concerns, please let me know.
